# Generated by Django 5.1.1 on 2024-09-22 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fittracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='goal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='fittracker.goal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='challenge',
            name='goal',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='challenge_goal', to='fittracker.goal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='fittracker.challenge'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('exercise', 'Exercise'), ('meditation', 'Meditation'), ('reading', 'Reading'), ('healthy_eating', 'Healthy Eating'), ('hydration', 'Hydration'), ('sleep', 'Sleep'), ('medicine', 'Medicine'), ('other', 'Other')], max_length=20),
        ),
    ]
