# Generated by Django 5.1.1 on 2024-09-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fittracker', '0002_activity_goal_challenge_goal_goal_challenge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='target_duration',
            field=models.IntegerField(default=300, help_text='Total duration required to complete the goal in minutes'),
            preserve_default=False,
        ),
    ]
